keosu_gadget_calendar_gadget_add:
    path:  /views/layout/gadget/eventgadget/add/{page}/{zone}
    defaults: { _controller: KeosuGadgetCalendarGadgetBundle:Edit:add }
    
keosu_gadget_calendar_gadget_edit:
    path:  /views/layout/gadget/eventgadget/edit/{page}/{zone}
    defaults: { _controller: KeosuGadgetCalendarGadgetBundle:Edit:edit }

keosu_gadget_calendar_gadget_service_viewone:
    path:  /service/gadget/calendar/view/{eventid}/{format}
    defaults: { _controller: KeosuGadgetCalendarGadgetBundle:Service:viewone}

keosu_gadget_calendar_gadget_service_view:
    path:  /service/gadget/calendar/{gadgetId}
    defaults: { _controller: KeosuGadgetCalendarGadgetBundle:Service:viewlist }
    
keosu_gadget_calendar_gadget_service_viewtable:
    path:  /service/gadget/calendar/{gadgetId}/{format}
    defaults: { _controller: KeosuGadgetCalendarGadgetBundle:Service:viewtable }

